pygments: true

# level 3
create_an_account: &create_an_account
  title:  Create an account
  parent: clever_cloud_usage
  ref:    create-an-account
php_start: &php_start
  title:  Start with PHP
  parent: php
  ref:    start-with-php
java_start: &java_start
  title:  Start with Java
  parent: java
  ref:    start-with-java
your_profile: &your_profile
  title:  Your profile
  parent: clever_cloud_usage
  ref:    your-profile
create_an_app: &create_an_app
  title:  Create an app
  parent: clever_cloud_usage
  ref:    create-an-app
add_database: &add_database
  title:  Add a database
  parent: services
  ref:    add-database
domain_name: &domain_name
  title:  Domain name
  parent: clever_cloud_usage
  ref:    domain-name
billing: &billing
  title:  Billing
  parent: clever_cloud_usage
  ref:    billing
pricing: &pricing
  title:  Pricing
  parent: clever_cloud_usage
  ref:    pricing
cc_conf: &cc_conf
  title:  Configuration file
  parent: clever_cloud_usage
  ref:    cc-conf
security: &security
  title:  Security
  parent: clever_cloud_usage
  ref:    security
ruby: &ruby
  title:  Ruby
  parent: ruby_apps
  ref:    ruby
jruby: &jruby
  title:  Jruby
  parent: ruby_apps
  ref:    jruby
ftp_deploy: &ftp_deploy
  title:  FTP deployment
  parent: php
  ref:    ftp-deploy
php_git_deploy: &php_git_deploy
  title:  Git deployment
  parent: php
  ref:    git-deploy
php_tested_cms: &php_tested_cms
  title:  Tested CMS
  parent: php
  ref:    tested-cms
git_deploy: &git_deploy
  title:  Git deployment
  parent: java
  ref:    git-deploy
mysql: &mysql
  title:  mySQL database
  parent: services
  ref:    mysql
postgresql: &postgresql
  title:  PostgreSQL database
  parent: services
  ref:    postgresql

# level 2
clever_cloud_usage: &clever_cloud_usage
  start: Yes
  title: Clever Cloud Usage
  ref:   clever-cloud-usage
  nav:
  - *create_an_account
  - *your_profile
  - *create_an_app
  - *domain_name
  - *billing
  - *pricing
  - *cc_conf
  - *security
php: &php
  title: PHP
  ref:   php
  nav:
  - *php_start
  - *ftp_deploy
  - *php_git_deploy
  - *php_tested_cms
java: &java
  title: Java
  ref:   java
  nav:
  - *java_start
  - *git_deploy
ruby_apps: &ruby_apps
  title: Ruby
  ref:   ruby
  nav:
  - *ruby
  - *jruby
services: &services
  title: Services
  ref:   services
  nav:
  - *mysql
  - *postgresql

# level 1
main:
  nav:
  - *clever_cloud_usage
  - *php
  - *java
  - *services
