# level 3 get started
create_an_account: &create_an_account
  title: Create an account
  parent: getting_started
  ref: create-an-account
your_profile: &your_profile
  title: Your profile
  parent: getting_started
  ref: your-profile
create_an_app: &create_an_app
  title: Create an app
  parent: getting_started
  ref: create-an-app
billing: &billing
  title: Billing
  parent: getting_started
  ref: billing
# level 3 app config
cc_conf: &cc_conf
  title: Deployment configuration
  parent: app_configuration
  ref: cc-conf
java_and_scala: &java_and_scala
  title: Java and scala
  parent: app_configuration
  ref: java-and-scala
php: &php
  title: PHP
  parent: app_configuration
  ref: php
ruby: &ruby
  title: Ruby
  parent: app_configuration
  ref: ruby
# level 2
getting_started: &getting_started
  start: Yes
  title: Getting started 
  ref: getting-started
  nav:
  - *create_an_account
  - *your_profile
  - *create_an_app
  - *billing
app_configuration: &app_configuration
  title: App configuration
  ref: app-configuration
  nav:
  - *cc_conf
  - *java_and_scala
  - *php
  - *ruby
# level 1
main:
  nav:
  - *getting_started
  - *app_configuration
