# site generation

tag_page_layout: tag_list
tag_page_dir:    articles

permalink: /:categories/:title/

pygments: true

# meta data

sidebar:
  tag_order:
  - Usage
  - Java
  - PHP
  - Services
  show_others: No
