# site generation

tag_page_layout: tag_list
tag_page_dir:    articles

permalink: /:categories/:title/

pygments: true

# meta data

portal:
  website: &portal_website
    title: Website
    url:   http://www.clever-cloud.com
  console: &portal_console
    title: Console
    url:   http://console.clever-cloud.com
  list: [*portal_website, *portal_console]

sidebar:
  tag_order:
  - Usage
  - Java
  - PHP
  - Services
  show_others: No
