pygments: true
# level 3 get started
create_an_account: &create_an_account
  title: Create an account
  parent: getting_started
  ref: create-an-account
php_start: &php_start
  title: Start with PHP
  parent: getting_started
  ref: start-with-php
java_start: &java_start
  title: Start with Java
  parent: getting_started
  ref: start-with-java
# level 3 console
your_profile: &your_profile
  title: Your profile
  parent: console_clever
  ref: your-profile
create_an_app: &create_an_app
  title: Create an app
  parent: console_clever
  ref: create-an-app
billing: &billing
  title: Billing
  parent: console_clever
  ref: billing
# level 3 app config
cc_conf: &cc_conf
  title: Configuration file
  parent: app_configuration
  ref: cc-conf
security: &security
  title: Security
  parent: app_configuration
  ref: security
java_and_scala: &java_and_scala
  title: Java and scala
  parent: app_configuration
  ref: java-and-scala
php: &php
  title: PHP
  parent: app_configuration
  ref: php
ruby: &ruby
  title: Ruby
  parent: app_configuration
  ref: ruby
jruby: &jruby
  title: Jruby
  parent: app_configuration
  ref: jruby
# level 3 app deploy
git_deploy: &git_deploy
  title: Git deployment
  parent: app_deployment
  ref: git-deploy
ftp_deploy: &ftp_deploy
  title: FTP deployment
  parent: app_deployment
  ref: ftp-deploy
# level 2
getting_started: &getting_started
  start: Yes
  title: Getting started 
  ref: getting-started
  nav:
  - *create_an_account
  - *php_start
  - *java_start
console_clever: &console_clever
  title: Clever Cloud Console 
  ref: console
  nav:
  - *your_profile
  - *create_an_app
  - *billing
app_configuration: &app_configuration
  title: App configuration
  ref: app-configuration
  nav:
  - *cc_conf
  - *security
  - *java_and_scala
  - *php
  - *ruby
  - *jruby
app_deployment: &app_deployment
  title: App deployment
  ref: app-deployment
  nav:
  - *git_deploy
  - *ftp_deploy
# level 1
main:
  nav:
  - *getting_started
  - *console_clever
  - *app_configuration
  - *app_deployment
